### ISSUE TITLE
Pathfinder player not working properly or at all

### ISSUE THREAD

**Issue by HarGabt** [xan1242/MPFmaster#5]
At first launch the prompt asked me to download net. 6.0.0. - I clicked yes, but was redirected to 6.0.11 version of net., which doesn't cooperate with the program - the player still insists on 6.0.0. version, which I eventually downloaded and installed afterwards. 
But even after that, the program doesn't even work - no sign of it doing anything - no UI or anything.

**Comment by xan1242** [comment]
Yeah dotnet is a bit weird.

You need .NET 6.0 *desktop* runtime. Not core runtime or anything else, *desktop*

**Comment by xan1242** [comment]
![image](https://user-images.githubusercontent.com/8014093/204111277-2b95e852-bef2-491f-9587-3a67d15d6245.png)

:/

It's not too clear to begin with within Visual Studio... Try Core and let me know the results...

**Comment by xan1242** [comment]
@HarGabt Did you manage to resolve this?

**Comment by HarGabt** [comment]
@xan1242 sorry, was busy

Okay, i just installed [Desktop runtime 6.0.11](https://download.visualstudio.microsoft.com/download/pr/0192a249-3ec8-4374-a827-e186dd58d55d/cec046575f3eb2247a10ba3d50f5cf6c/windowsdesktop-runtime-6.0.11-win-x64.exe) and now it works!

**Comment by xan1242** [comment]
Awesome, I'll add it in the description, just in case...
